from typing import Dict, List
from homeassistant.const import Platform

from custom_components.regulus.schema import sensor
from .dashboard_schemas import DashboardResponseSchema
from ...service.abstract_api import AbstractApi
from ...service.xml_parser_service import get_value_from_map

class DashboardApi(AbstractApi[DashboardResponseSchema]):
    page = "/1_sch.xml"

    def generate_response(self, schema_xml_map: Dict[str, str], registry_errors: List[str]) -> DashboardResponseSchema:
        print("Successfully fetched `/dashboard` data")
        version = self.config["ir_version"]

        return DashboardResponseSchema(
            outdoorTemperature = sensor("Outdoor Temperature", 
                                        get_value_from_map(schema_xml_map, "outdoorTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            rcTariff = sensor("RC Tariff", 
                                          get_value_from_map(schema_xml_map, "rcTariff", registry_errors, version) == "1",
                                          "", "none", "mdi:cash-clock", Platform.BINARY_SENSOR),
            holiday = sensor("Holiday", 
                                          get_value_from_map(schema_xml_map, "holiday", registry_errors, version) == "1",
                                          "", "none", "mdi:beach", Platform.BINARY_SENSOR),
            heatPumpRunningStatus= sensor("Heat Pump Running Status", 
                                          get_value_from_map(schema_xml_map, "heatPumpRunningStatus", registry_errors, version) != "0",
                                          "", "running", "mdi:fan", Platform.BINARY_SENSOR),
            heatPumpOutletTemperature = sensor("Heat Pump Outlet Temperature", 
                                        get_value_from_map(schema_xml_map, "heatPumpOutletTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            heatPumpInletTemperature = sensor("Heat Pump Inlet Temperature", 
                                        get_value_from_map(schema_xml_map, "heatPumpInletTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            zone1Status = sensor("Zone 1 Running Status", 
                                          get_value_from_map(schema_xml_map, "zone1RunningStatus", registry_errors, version) != "0",
                                          "", "running", "mdi:heating-coil", Platform.BINARY_SENSOR),
            zone1ActualTemperature = sensor("Zone 1 Temperature", 
                                        get_value_from_map(schema_xml_map, "zone1Temperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            zone1RequiredTemperature = sensor("Zone 1 Required Temperature", 
                                        get_value_from_map(schema_xml_map, "zone1RequiredTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            zone1ActualHeatingWaterTemperature = sensor("Zone 1 Heating Water Temperature", 
                                        get_value_from_map(schema_xml_map, "zone1HeatingWaterTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            zone1RequiredHeatingWaterTemperature = sensor("Zone 1 Required Heating Water Temperature", 
                                        get_value_from_map(schema_xml_map, "zone1RequiredHeatingWaterTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            zone2Status = sensor("Zone 2 Running Status", 
                                          get_value_from_map(schema_xml_map, "zone2RunningStatus", registry_errors, version) != "0",
                                          "", "running", "mdi:radiator", Platform.BINARY_SENSOR),
            zone2ActualTemperature = sensor("Zone 2 Temperature", 
                                        get_value_from_map(schema_xml_map, "zone2Temperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            zone2RequiredTemperature = sensor("Zone 2 Required Temperature", 
                                        get_value_from_map(schema_xml_map, "zone2RequiredTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            zone2ActualHeatingWaterTemperature = sensor("Zone 2 Heating Water Temperature", 
                                        get_value_from_map(schema_xml_map, "zone2HeatingWaterTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            zone2RequiredHeatingWaterTemperature = sensor("Zone 2 Required Heating Water Temperature", 
                                        get_value_from_map(schema_xml_map, "zone2RequiredHeatingWaterTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            akuStatus = sensor("Aku Running Status", 
                                          get_value_from_map(schema_xml_map, "akuRunningStatusFromHeatPump", registry_errors, version) == "1",
                                          "", "running", "mdi:water-boiler", Platform.BINARY_SENSOR),
            akuTopTemperature = sensor("Aku Top Temperature", 
                                        get_value_from_map(schema_xml_map, "akuTopTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            akuBottomTemperature = sensor("Aku Bottom Temperature", 
                                        get_value_from_map(schema_xml_map, "akuBottomTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            akuRequiredTemperature = sensor("Aku Required Temperature", 
                                        get_value_from_map(schema_xml_map, "akuRequiredTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            waterStatus = sensor("Water Running Status", 
                                          get_value_from_map(schema_xml_map, "waterRunningStatusFromHeatPump", registry_errors, version) == "1",
                                          "", "running", "mdi:water", Platform.BINARY_SENSOR),
            waterActualTemperature = sensor("Water Actual Temperature", 
                                        get_value_from_map(schema_xml_map, "waterSwitchingSensorTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            waterRequiredTemperature = sensor("Water Required Temperature", 
                                        get_value_from_map(schema_xml_map, "waterRequiredTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            solarStatus = sensor("Solar Status", 
                                        get_value_from_map(schema_xml_map, "solarRunningStatus", registry_errors, version) == "1", 
                                      "", "running", "mdi:solar-panel", Platform.BINARY_SENSOR),
            solarPanelTemperature = sensor("Solar Panel Temperature", 
                                        get_value_from_map(schema_xml_map, "solarPanelTemperature", registry_errors, version), 
                                      "°C", "temperature", "mdi:thermometer", Platform.SENSOR),
            circulationStatus = sensor("Circulation Status", 
                                        get_value_from_map(schema_xml_map, "circulationRunningStatus", registry_errors, version) == "1", 
                                      "", "running", "mdi:sync", Platform.BINARY_SENSOR),
        )
