name: HACS Validation

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
